In [1]:
!wget http://christianbenner.com/finemap_v1.4.1_x86_64.tgz
!tar xvf finemap_v1.4.1_x86_64.tgz

--2026-01-29 10:43:55--  http://christianbenner.com/finemap_v1.4.1_x86_64.tgz
Resolving christianbenner.com (christianbenner.com)... 92.205.4.208
Connecting to christianbenner.com (christianbenner.com)|92.205.4.208|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2152409 (2.1M) [application/x-tar]
Saving to: ‘finemap_v1.4.1_x86_64.tgz’

finemap_v1.4.1_x86_ 100%[===================>]   2.05M  2.54MB/s    in 0.8s

2026-01-29 10:43:56 (2.54 MB/s) - ‘finemap_v1.4.1_x86_64.tgz’ saved [2152409/2152409]

finemap_v1.4.1_x86_64/
finemap_v1.4.1_x86_64/LICENSE
finemap_v1.4.1_x86_64/example/
finemap_v1.4.1_x86_64/example/data.z
finemap_v1.4.1_x86_64/example/data.ld
finemap_v1.4.1_x86_64/example/data.k
finemap_v1.4.1_x86_64/example/data
finemap_v1.4.1_x86_64/finemap_v1.4.1_x86_64

In [2]:
!wget http://www.christianbenner.com/ldstore_v2.0_x86_64.tgz
!tar xzvf ldstore_v2.0_x86_64.tgz

--2026-01-29 10:44:15--  http://www.christianbenner.com/ldstore_v2.0_x86_64.tgz
Resolving www.christianbenner.com (www.christianbenner.com)... 92.205.4.208
Connecting to www.christianbenner.com (www.christianbenner.com)|92.205.4.208|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5299934 (5.1M) [application/x-tar]
Saving to: ‘ldstore_v2.0_x86_64.tgz’

ldstore_v2.0_x86_64 100%[===================>]   5.05M  5.44MB/s    in 0.9s

2026-01-29 10:44:17 (5.44 MB/s) - ‘ldstore_v2.0_x86_64.tgz’ saved [5299934/5299934]

ldstore_v2.0_x86_64/
ldstore_v2.0_x86_64/example/
ldstore_v2.0_x86_64/example/data
ldstore_v2.0_x86_64/example/data.bgen
ldstore_v2.0_x86_64/example/data.bgen.bgi
ldstore_v2.0_x86_64/example/data.sample
ldstore_v2.0_x86_64/example/data.z
ldstore_v2.0_x86_64/ldstore_v2.0_x86_64
ldstore_v2.0_x86_64/LICENSE

In [3]:
!cp mdd2024_his_hg38_snpvar.tsv mdd2024_amr_hg38_snpvar.parquet

In [ ]:
mkdir -p LD_cache

clusters=(afr amr eas eur sas)
sumstats=(mdd2024_afr mdd2024_eas mdd2024_his mdd2025_eur mdd2024_sas)
ns=(70727 58319 16211 14979 1577200)

for ((i=0 ; i < ${#clusters[@]} ; ++i)); do
    cluster=${clusters[i]}
    sums=${sumstats[i]}
    n=${ns[i]}

    python polyfun/finemapper.py \
        --geno acaf_chr11_61000000-63000000_${cluster} \
        --sumstats ${sums}_hg38_snpvar.tsv \
        --n $n \
        --chr 11 \
        --start 61600000 \
        --end 62000000 \
        --method finemap \
        --finemap-exe finemap_v1.4.1_x86_64/finemap_v1.4.1_x86_64 \
        --max-num-causal 5 \
        --allow-missing \
        --cache-dir LD_cache \
        --out ${sums}_polyfun_finemap_acaf_hg38_chr11_61600000-6200000.tsv
done

In [4]:
import pandas as pd

In [17]:
afr = pd.read_csv("mdd2024_afr_polyfun_finemap_acaf_hg38_chr11_61600000-6200000.tsv", sep = "\t")
amr = pd.read_csv("mdd2024_his_polyfun_finemap_acaf_hg38_chr11_61600000-6200000.tsv", sep = "\t")
eas = pd.read_csv("mdd2024_eas_polyfun_finemap_acaf_hg38_chr11_61600000-6200000.tsv", sep = "\t")
eur = pd.read_csv("mdd2025_eur_polyfun_finemap_acaf_hg38_chr11_61600000-6200000.tsv", sep = "\t")
sas = pd.read_csv("mdd2024_sas_polyfun_finemap_acaf_hg38_chr11_61600000-6200000.tsv", sep = "\t")

In [18]:
afr[afr["PIP"].eq(afr.groupby("CREDIBLE_SET")["PIP"].transform("max"))]

,SNP,CHR,BP,A1,A2,PIP,BETA_MEAN,BETA_SD,DISTANCE_FROM_CENTER,CREDIBLE_SET
0,rs198456,11,61695916,A,G,0.275332,-0.003355,0.005801,104616,1
1,rs17827918,11,61700693,G,A,0.167983,-0.002281,0.005307,99839,2
162,rs533292,11,61711058,A,C,0.000653,-0.000007,0.000287,89474,0

In [19]:
amr[amr["PIP"].eq(amr.groupby("CREDIBLE_SET")["PIP"].transform("max"))]

,SNP,CHR,BP,A1,A2,PIP,BETA_MEAN,BETA_SD,DISTANCE_FROM_CENTER,CREDIBLE_SET
0,rs115430155,11,61984156,T,A,0.640500,-0.071066,0.055547,184277,3
1,rs17156616,11,61975806,T,C,0.590763,0.067910,0.058555,175927,2
2,rs57398279,11,61971670,G,C,0.103371,-0.004513,0.014656,171791,1
3,rs2009875,11,61946560,A,G,0.078632,-0.003964,0.013889,146681,0

In [20]:
eas[eas["PIP"].eq(eas.groupby("CREDIBLE_SET")["PIP"].transform("max"))]

,SNP,CHR,BP,A1,A2,PIP,BETA_MEAN,BETA_SD,DISTANCE_FROM_CENTER,CREDIBLE_SET
0,rs7115739,11,61874245,T,G,0.717595,0.030316,0.020235,72380,2
1,rs2727260,11,61944770,C,T,0.573750,-0.025087,0.022399,142905,1
3,rs174464,11,61890454,A,G,0.146646,0.003055,0.007866,88589,4
8,rs174455,11,61888645,G,A,0.078682,0.001595,0.005692,86780,3
21,rs174570,11,61829740,C,T,0.011527,-0.000214,0.002114,27875,0

In [21]:
eur[eur["PIP"].eq(eur.groupby("CREDIBLE_SET")["PIP"].transform("max"))]

,SNP,CHR,BP,A1,A2,PIP,BETA_MEAN,BETA_SD,DISTANCE_FROM_CENTER,CREDIBLE_SET
0,rs12805732,11,61680912,G,A,0.445584,0.017520,0.020456,118967,3
1,rs174583,11,61842278,C,T,0.265000,-0.017799,0.030489,42399,1
7,rs198433,11,61717104,A,G,0.073993,-0.002972,0.010833,82775,2
17,rs174549,11,61803910,G,A,0.022659,-0.001537,0.010213,4031,0

In [22]:
sas[sas["PIP"].eq(sas.groupby("CREDIBLE_SET")["PIP"].transform("max"))]

,SNP,CHR,BP,A1,A2,PIP,BETA_MEAN,BETA_SD,DISTANCE_FROM_CENTER,CREDIBLE_SET
0,rs498793,11,61857233,T,C,0.068925,-1.575800e-04,0.000616,55761,1
223,rs198460,11,61757502,G,A,0.001123,-9.731500e-08,0.000027,43970,0