# Polyfun with pre-computed priors

In [3]:
from pyprojroot.here import here
import pandas as pd

Annotate SNPs with [pre-computed priors](https://github.com/omerwe/polyfun/wiki/1.-Computing-prior-causal-probabilities-with-PolyFun#polyfun-approach-1-using-precomputed-prior-causal-probabilities-based-on-a-meta-analysis-of-15-uk-biobank-traits). There are very few missing SNPs apart from chrX, so allow missing.

In [11]:
%%bash -s {here()}
here=$1
mkdir $here/data/processed/snpvar

python $here/vendor/polyfun/extract_snpvar.py \
    --sumstats $here/data/processed/sumstats/mdd2025_eur_hg19_z.tsv \
    --allow-missing \
    --out $here/data/processed/snpvar/mdd2025_eur_hg19_snpvar.gz

[INFO]  Loading sumstats files...
[INFO]  Done in 25.86 seconds
[INFO]  Loading meta-analyzed per-SNP-h2 files...
[INFO]  Done in 63.06 seconds
[INFO]  Merging sumstats with per-SNP h2 data...
[INFO]  Flipping the Z-sign of 5658139 SNPs that A1 in sumstats = A2 in the per-SNP h2 data
[INFO]  Done in 20.49 seconds
[WARNING]  Not all SNPs in the SNPs file were found in the meta file. Wrote a list of missing SNPs to /home/madams23/Projects/cvd-mh-loci/data/processed/snpvar/mdd2025_eur_hg19_snpvar.gz.miss.gz
[INFO]  Writing output file to /home/madams23/Projects/cvd-mh-loci/data/processed/snpvar/mdd2025_eur_hg19_snpvar.gz

mkdir: cannot create directory ‘/home/madams23/Projects/cvd-mh-loci/data/processed/snpvar’: File exists

In [ ]:
%%bash -s {here()}
here=$1

mkdir -p $here/data/cache/ld
mkdir -p $here/data/results/PolyFun

python $here/vendor/polyfun/finemapper.py \
    --geno $here/data/processed/reference/all_h19_EUR_chr11_61000000-63000000 \
    --sumstats $here/data/processed/snpvar/mdd2025_eur_hg19_snpvar.gz \
    --n 1577200 \
    --chr 11 \
    --start 61400000 \
    --end 61700000 \
    --method susie \
    --max-num-causal 5 \
    --cache-dir $here/data/cache/ld \
    --out $here/data/results/PolyFun/mdd2025_eur_polyfun_susie_chr11_61400000-61700000.gz

*********************************************************************
* Fine-mapping Wrapper
* Version 1.0.0
* (C) 2019-2024 Omer Weissbrod
*********************************************************************

[INFO]  Loading sumstats file...
[INFO]  Loaded sumstats for 351143 SNPs in 8.99 seconds
[INFO]  cffi mode is CFFI_MODE.ANY
[DEBUG]  Looking for R home with: R RHOME
[INFO]  R home found: /home/madams23/Projects/cvd-mh-loci/.pixi/envs/polyfun/lib/R
[DEBUG]  Looking for LD_LIBRARY_PATH with: /home/madams23/Projects/cvd-mh-loci/.pixi/envs/polyfun/lib/R/bin/Rscript -e cat(Sys.getenv("LD_LIBRARY_PATH"))
[INFO]  R library path:
[INFO]  LD_LIBRARY_PATH:
[DEBUG]  cffi mode is InterfaceType.API
[INFO]  Default options to initialize R: rpy2, --quiet, --no-save
[INFO]  R is already initialized. No need to initialize.
[INFO]  Found a cached LD file containing all SNPs with sumstats in chromosome 11 BP 61400000-61700000: /home/madams23/Projects/cvd-mh-loci/data/cache/ld/all_h19_EUR_chr11_61000000-63000000.11.61400000.61700000.npz
[INFO]  Loading LD file /home/madams23/Projects/cvd-mh-loci/data/cache/ld/all_h19_EUR_chr11_61000000-63000000.11.61400000.61700000
[INFO]  Done in 1.38 seconds
[INFO]  Starting functionally-informed SuSiE fine-mapping for chromosome 11 BP 61400000-61700000 (589 SNPs)
[INFO]  Using susieR::susie_suff_stat()
[INFO]  Done in 0.28 seconds
[INFO]  Using rpy2 version 3.5.11
[INFO]  Writing fine-mapping results to /home/madams23/Projects/cvd-mh-loci/data/results/PolyFun/mdd2025_eur_polyfun_susie_chr11_61400000-61700000.gz

In [18]:
susie = fads = pd.read_csv(
    here("data/results/PolyFun/mdd2025_eur_polyfun_susie_chr11_61400000-61700000.gz"),
    sep = "\t",
    compression = "infer"
)

susie_cr = (
    susie
    .query("CREDIBLE_SET != 0 and PIP >= 0.05")[["CREDIBLE_SET", "SNP", "P", "PIP"]]
    .sort_values(by=["CREDIBLE_SET", "PIP"], ascending=[True, False])
)

susie_cr

   CREDIBLE_SET         SNP             P       PIP
1             1    rs174561  7.925300e-20  0.290706
2             1    rs174544  1.702760e-20  0.232573
5             1     rs99780  4.950110e-20  0.117866
7             1    rs174583  3.261250e-20  0.099338
8             1    rs174548  3.738480e-21  0.060067
0             2  rs12805732  7.896210e-10  0.365918
3             2    rs198462  9.884900e-13  0.191245
4             2    rs198465  2.568780e-12  0.123473
6             2    rs198476  9.884900e-13  0.107409

In [ ]:
%%bash -s {here()}
here=$1

mkdir -p $here/data/cache/ld
mkdir -p $here/data/results/PolyFun

python $here/vendor/polyfun/finemapper.py \
    --geno $here/data/processed/reference/all_h19_EUR_chr11_61000000-63000000 \
    --sumstats $here/data/processed/snpvar/mdd2025_eur_hg19_snpvar.gz \
    --n 1577200 \
    --chr 11 \
    --start 61400000 \
    --end 61700000 \
    --method finemap \
    --finemap-exe $here/vendor/finemap \
    --max-num-causal 5 \
    --cache-dir $here/data/cache/ld \
    --out $here/data/results/PolyFun/mdd2025_eur_polyfun_finemap_chr11_61400000-61700000.gz

*********************************************************************
* Fine-mapping Wrapper
* Version 1.0.0
* (C) 2019-2024 Omer Weissbrod
*********************************************************************

[INFO]  Loading sumstats file...
[INFO]  Loaded sumstats for 351143 SNPs in 8.80 seconds
[INFO]  Found a cached LD file containing all SNPs with sumstats in chromosome 11 BP 61400000-61700000: /home/madams23/Projects/cvd-mh-loci/data/cache/ld/all_h19_EUR_chr11_61000000-63000000.11.61400000.61700000.npz
[INFO]  Loading LD file /home/madams23/Projects/cvd-mh-loci/data/cache/ld/all_h19_EUR_chr11_61000000-63000000.11.61400000.61700000
[INFO]  Done in 1.37 seconds
[INFO]  Starting functionally-informed FINEMAP fine-mapping for chromosome 11 BP 61400000-61700000 (589 SNPs)
[INFO]  Running FINEMAP...
[INFO]  done in 2.21 seconds
[INFO]  Done in 2.25 seconds
[INFO]  Writing fine-mapping results to /home/madams23/Projects/cvd-mh-loci/data/results/PolyFun/mdd2025_eur_polyfun_finemap_chr11_61400000-61700000.gz

In [17]:
finemap = fads = pd.read_csv(
    here("data/results/PolyFun/mdd2025_eur_polyfun_finemap_chr11_61400000-61700000.gz"),
    sep = "\t",
    compression = "infer"
)

finemap_cr = (
    finemap
    .query("CREDIBLE_SET != 0 and PIP >= 0.05")[["CREDIBLE_SET", "SNP", "PIP"]]
    .sort_values(by=["CREDIBLE_SET", "PIP"], ascending=[True, False])
)

finemap_cr

   CREDIBLE_SET         SNP       PIP
4             1     rs99780  0.148331
5             1    rs174583  0.134190
8             2    rs198433  0.072924
0             3  rs12805732  0.336035
1             3    rs174561  0.267692
2             3    rs174544  0.211795
3             3    rs198462  0.166639
6             3    rs198465  0.102835
7             3    rs198476  0.092977

In [13]:
finemap

,SNP,CHR,BP,A1,A2,PIP,BETA_MEAN,BETA_SD,DISTANCE_FROM_CENTER,CREDIBLE_SET
0,rs12805732,11,61448384,G,A,0.336035,1.342500e-03,0.001947,101447,3
1,rs174561,11,61582708,T,C,0.267692,-1.729530e-03,0.002898,32877,3
2,rs174544,11,61567753,C,A,0.211795,-1.402000e-03,0.002735,17922,3
3,rs198462,11,61524119,G,A,0.166639,6.650800e-04,0.001528,25712,3
4,rs99780,11,61596633,C,T,0.148331,-9.772270e-04,0.002370,46802,1
...,...,...,...,...,...,...,...,...,...,...
584,rs10897183,11,61683392,C,A,0.000002,-2.384840e-12,0.000001,133561,0
585,rs117664091,11,61679346,C,T,0.000002,-8.453020e-11,0.000001,129515,0
586,rs117609511,11,61447355,C,T,0.000002,1.746540e-10,0.000001,102476,0
587,rs174569,11,61594164,T,C,0.000002,7.603640e-11,0.000001,44333,0
588,rs188021317,11,61522383,G,A,0.000002,1.091150e-10,0.000001,27448,0