# SuSiEx with reference panel

In [1]:
import polars as pl
from pyprojroot.here import here

Prepare sumstats

In [2]:
# filter out null/unmatched variants
qc_mask = pl.any_horizontal(
    pl.all().is_null()
)

for dataset in ["mdd2024_afr", "mdd2024_eas", "mdd2024_his", "mdd2025_eur", "mdd2024_sas"]:
    sumstats = pl.scan_parquet(here(f"data/processed/sumstats/tidy/{dataset}/tidyGWAS_hivestyle"))
    susie = (sumstats
    .select(
        pl.col("CHR"),
        pl.col("RSID").alias("SNP"),
        pl.col("POS_37").alias("BP"),
        pl.col("EffectAllele").alias("A1"),
        pl.col("OtherAllele").alias("A2"),
        pl.col("B").alias("BETA"),
        pl.col("SE"),
        pl.col("P")
    )
    .filter(~qc_mask)
    )

    susie.sink_csv(here(f"data/processed/sumstats/{dataset}_hg19_susie.tsv"), separator = "\t")

Run SuSiEx

In [21]:
%%bash -s {here()}
here=$1
sumstats=${here}/data/processed/sumstats
reference=${here}/data/processed/reference

sumstats_afr=${sumstats}/mdd2024_afr_hg19_susie.tsv
sumstats_eas=${sumstats}/mdd2024_eas_hg19_susie.tsv
sumstats_his=${sumstats}/mdd2024_his_hg19_susie.tsv
sumstats_sas=${sumstats}/mdd2024_sas_hg19_susie.tsv
sumstats_eur=${sumstats}/mdd2025_eur_hg19_susie.tsv 

ref_afr=${reference}/all_hg19_AFR_chr11_61000000-63000000
ref_eas=${reference}/all_hg19_EAS_chr11_61000000-63000000
ref_amr=${reference}/all_hg19_AMR_chr11_61000000-63000000
ref_sas=${reference}/all_hg19_SAS_chr11_61000000-63000000
ref_eur=${reference}/all_hg19_EUR_chr11_61000000-63000000

ld_afr=${reference}/ld/all_hg19_AFR_chr11_61000000-63000000
ld_eas=${reference}/ld/all_hg19_EAS_chr11_61000000-63000000
ld_amr=${reference}/ld/all_hg19_AMR_chr11_61000000-63000000
ld_sas=${reference}/ld/all_hg19_SAS_chr11_61000000-63000000
ld_eur=${reference}/ld/all_hg19_EUR_chr11_61000000-63000000

mkdir -p ${reference}/ld
mkdir -p ${here}/data/results/SuSiEx

$here/vendor/SuSiEx/bin_static/SuSiEx \
  --sst_file=$sumstats_afr,$sumstats_eas,$sumstats_his,$sumstats_sas,$sumstats_eur \
  --n_gwas=70727,58319,16211,14979,1577200 \
  --ref_file=$ref_afr,$ref_eas,$ref_amr,$ref_sas,$ref_eur \
  --ld_file=$ld_afr,$ld_eas,$ld_amr,$ld_sas,$ld_eur \
  --out_dir=${here}/reports/tables/SuSiEx \
  --out_name=mdd_all_hg19_chr11_61000000-63000000 \
  --chr=11 \
  --bp=61000000,63000000 \
  --chr_col=1,1,1,1,1 \
  --snp_col=2,2,2,2,2 \
  --bp_col=3,3,3,3,3 \
  --a1_col=4,4,4,4,4 \
  --a2_col=5,5,5,5,5 \
  --eff_col=6,6,6,6,6 \
  --se_col=7,7,7,7,7 \
  --pval_col=8,8,8,8,8 \
  --plink=${here}/.pixi/envs/default/bin/plink \
  --keep-ambig=True \
  --maf=0.005 \
  --mult-step=True \
  --pval_thresh=1e-5 \
  --max_iter=500 \
  --tol=1e-4 \
  --threads=8

Software parameters:
--sst_file = /home/madams23/Projects/cvd-mh-loci/data/processed/sumstats/mdd2024_afr_hg19_susie.tsv,/home/madams23/Projects/cvd-mh-loci/data/processed/sumstats/mdd2024_eas_hg19_susie.tsv,/home/madams23/Projects/cvd-mh-loci/data/processed/sumstats/mdd2024_his_hg19_susie.tsv,/home/madams23/Projects/cvd-mh-loci/data/processed/sumstats/mdd2024_sas_hg19_susie.tsv,/home/madams23/Projects/cvd-mh-loci/data/processed/sumstats/mdd2025_eur_hg19_susie.tsv
--ld_file = /home/madams23/Pro

jects/cvd-mh-loci/data/processed/reference/ld/all_hg19_AFR_chr11_61000000-63000000,/home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_EAS_chr11_61000000-63000000,/home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_AMR_chr11_61000000-63000000,/home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_SAS_chr11_61000000-63000000,/home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_EUR_chr11_61000000-63000000
--n_gwas = 70727,58319,16211,14979,1577200
--out_dir = /home/madams23/Projects/cvd-mh-loci/reports/tables/SuSiEx
--out_name = mdd_all_hg19_chr11_61000000-63000000
--chr = 11
--bp = 61000000,63000000
--chr_col = 1,1,1,1,1
--snp_col = 2,2,2,2,2
--bp_col = 3,3,3,3,3
--a1_col = 4,4,4,4,4
--a2_col = 5,5,5,5,5
--eff_col = 6,6,6,6,6
--se_col = 7,7,7,7,7
--pval_col = 8,8,8,8,8
--plink = /home/madams23/Projects/cvd-mh-loci/.pixi/envs/default/bin/plink
--keep-ambig = true
--mult-step = true
--precmp = true
--maf = 0.005
--level = 0.95
--min_purity = 0.5
--pval_thresh = 1e-05
--tol = 0.0001
--n_sig = 5
--max_iter = 500
--threads = 8
... parse reference file: /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_AFR_chr11_61000000-63000000_ref.bim ...
... 12436 SNPs in the fine-mapping region read from /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_AFR_chr11_61000000-63000000_ref.bim ...
... 9137 SNPs in the fine-mapping region read from /home/madams23/Projects/cvd-mh-loci/data/processed/sumstats/mdd2024_afr_hg19_susie.tsv ...
... parse reference file: /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_EAS_chr11_61000000-63000000_ref.bim ...
... 5825 SNPs in the fine-mapping region read from /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_EAS_chr11_61000000-63000000_ref.bim ...
... 4130 SNPs in the fine-mapping region read from /home/madams23/Projects/cvd-mh-loci/data/processed/sumstats/mdd2024_eas_hg19_susie.tsv ...
... parse reference file: /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_AMR_chr11_61000000-63000000_ref.bim ...
... 8387 SNPs in the fine-mapping region read from /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_AMR_chr11_61000000-63000000_ref.bim ...
... 7975 SNPs in the fine-mapping region read from /home/madams23/Projects/cvd-mh-loci/data/processed/sumstats/mdd2024_his_hg19_susie.tsv ...
... parse reference file: /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_SAS_chr11_61000000-63000000_ref.bim ...
... 7306 SNPs in the fine-mapping region read from /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_SAS_chr11_61000000-63000000_ref.bim ...
... 3030 SNPs in the fine-mapping region read from /home/madams23/Projects/cvd-mh-loci/data/processed/sumstats/mdd2024_sas_hg19_susie.tsv ...
... parse reference file: /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_EUR_chr11_61000000-63000000_ref.bim ...
... 6430 SNPs in the fine-mapping region read from /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_EUR_chr11_61000000-63000000_ref.bim ...
... 4095 SNPs in the fine-mapping region read from /home/madams23/Projects/cvd-mh-loci/data/processed/sumstats/mdd2025_eur_hg19_susie.tsv ...
... 10615 common SNPs in the reference and sumstats ...
... parse LD file: /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_AFR_chr11_61000000-63000000.ld.bin ...
... (12436,12436) LD matrix read from /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_AFR_chr11_61000000-63000000.ld.bin ...
... parse LD file: /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_EAS_chr11_61000000-63000000.ld.bin ...
... (5825,5825) LD matrix read from /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_EAS_chr11_61000000-63000000.ld.bin ...
... parse LD file: /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_AMR_chr11_61000000-63000000.ld.bin ...
... (8387,8387) LD matrix read from /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_AMR_chr11_61000000-63000000.ld.bin ...
... parse LD file: /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_SAS_chr11_61000000-63000000.ld.bin ...
... (7306,7306) LD matrix read from /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_SAS_chr11_61000000-63000000.ld.bin ...
... parse LD file: /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_EUR_chr11_61000000-63000000.ld.bin ...
... (6430,6430) LD matrix read from /home/madams23/Projects/cvd-mh-loci/data/processed/reference/ld/all_hg19_EUR_chr11_61000000-63000000.ld.bin ...
* Mult-step model fitting *
... fit SuSiEx model with 5 signals...
--- iter-1 ---
--- iter-2 ---
--- iter-3 ---
--- iter-4 ---
--- iter-5 ---
--- iter-6 ---
--- iter-7 ---
--- iter-8 ---
... write credible sets to file: /home/madams23/Projects/cvd-mh-loci/reports/tables/SuSiEx/mdd_all_hg19_chr11_61000000-63000000.summary/.cs/.snp ...

Parse results

In [22]:
cs = pl.read_csv(here("reports/tables/SuSiEx/mdd_all_hg19_chr11_61000000-63000000.cs"), separator="\t")
snp = pl.read_csv(here("reports/tables/SuSiEx/mdd_all_hg19_chr11_61000000-63000000.snp"), separator="\t")
summary = pl.read_csv(here("reports/tables/SuSiEx/mdd_all_hg19_chr11_61000000-63000000.summary"), separator="\t", comment_prefix="#")

In [23]:
summary

shape: (2, 17)
┌───────┬───────────┬───────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ CS_ID ┆ CS_LENGTH ┆ CS_PURITY ┆ MAX_PIP_SN ┆ … ┆ POST-HOC_P ┆ POST-HOC_P ┆ POST-HOC_ ┆ POST-HOC_ │
│ ---   ┆ ---       ┆ ---       ┆ P          ┆   ┆ ROB_POP2   ┆ ROB_POP3   ┆ PROB_POP4 ┆ PROB_POP5 │
│ i64   ┆ i64       ┆ f64       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│       ┆           ┆           ┆ str        ┆   ┆ f64        ┆ f64        ┆ f64       ┆ i64       │
╞═══════╪═══════════╪═══════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 1     ┆ 4         ┆ 0.998286  ┆ rs28456    ┆ … ┆ 0.346873   ┆ 0.432911   ┆ 0.343089  ┆ 1         │
│ 2     ┆ 32        ┆ 0.811537  ┆ rs11283070 ┆ … ┆ 0.352458   ┆ 0.405294   ┆ 0.326591  ┆ 1         │
│       ┆           ┆           ┆ 0          ┆   ┆            ┆            ┆           ┆           │
└───────┴───────────┴───────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [24]:
cs

shape: (36, 11)
┌───────┬────────────┬──────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ CS_ID ┆ SNP        ┆ BP       ┆ REF_ALLELE ┆ … ┆ SE         ┆ -LOG10P    ┆ CS_PIP    ┆ OVRL_PIP  │
│ ---   ┆ ---        ┆ ---      ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64   ┆ str        ┆ i64      ┆ str        ┆   ┆ str        ┆ str        ┆ f64       ┆ f64       │
╞═══════╪════════════╪══════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 1     ┆ rs28456    ┆ 61589481 ┆ A,A,A,A,A  ┆ … ┆ 0.00835653 ┆ 1.94909,0. ┆ 0.458328  ┆ 0.458328  │
│       ┆            ┆          ┆            ┆   ┆ ,0.0058817 ┆ 821865,1.3 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ 2,0.011244 ┆ 6261,0.544 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ …          ┆ …          ┆           ┆           │
│ 1     ┆ rs174548   ┆ 61571348 ┆ C,C,C,C,C  ┆ … ┆ 0.00694488 ┆ 1.73849,0. ┆ 0.381283  ┆ 0.381283  │
│       ┆            ┆          ┆            ┆   ┆ ,0.0058828 ┆ 757992,1.3 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ 4,0.011288 ┆ 4894,0.525 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ …          ┆ …          ┆           ┆           │
│ 1     ┆ rs174560   ┆ 61581764 ┆ T,T,T,T,T  ┆ … ┆ 0.00698032 ┆ 1.65941,0. ┆ 0.099673  ┆ 0.099673  │
│       ┆            ┆          ┆            ┆   ┆ ,0.0058817 ┆ 716661,1.3 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ 2,0.011283 ┆ 3505,0.515 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ …          ┆ …          ┆           ┆           │
│ 1     ┆ rs174549   ┆ 61571382 ┆ G,G,G,G,G  ┆ … ┆ 0.0187277, ┆ 0.902417,0 ┆ 0.0293262 ┆ 0.0293262 │
│       ┆            ┆          ┆            ┆   ┆ 0.00588284 ┆ .706487,1. ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ ,0.0112153 ┆ 36543,0.53 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ …          ┆ …          ┆           ┆           │
│ 2     ┆ rs11283070 ┆ 61133980 ┆ NA,NA,G,NA ┆ … ┆ NA,NA,0.02 ┆ NA,NA,0.74 ┆ 0.334592  ┆ 0.334592  │
│       ┆ 0          ┆          ┆ ,G         ┆   ┆ 25536,NA,0 ┆ 2754,NA,9. ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ .00174337  ┆ 71936      ┆           ┆           │
│ …     ┆ …          ┆ …        ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 2     ┆ rs35605696 ┆ 61231177 ┆ A,A,A,A,A  ┆ … ┆ 0.00602311 ┆ 1.63445,0. ┆ 0.0059106 ┆ 0.0059106 │
│       ┆            ┆          ┆            ┆   ┆ ,0.0192098 ┆ 461283,0.2 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ ,0.0172023 ┆ 35249,0.07 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ …          ┆ …          ┆           ┆           │
│ 2     ┆ rs28720282 ┆ 61090956 ┆ NA,NA,T,NA ┆ … ┆ NA,NA,0.02 ┆ NA,NA,0.63 ┆ 0.005834  ┆ 0.005834  │
│       ┆            ┆          ┆ ,T         ┆   ┆ 25536,NA,0 ┆ 7736,NA,9. ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ .00171852  ┆ 05995      ┆           ┆           │
│ 2     ┆ rs3018734  ┆ 61211286 ┆ A,NA,A,A,A ┆ … ┆ 0.00758848 ┆ 1.05049,NA ┆ 0.005606  ┆ 0.005606  │
│       ┆            ┆          ┆            ┆   ┆ ,NA,0.0205 ┆ ,0.0777168 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ 534,0.0244 ┆ ,0.0243911 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ …          ┆ …          ┆           ┆           │
│ 2     ┆ rs3019192  ┆ 61268257 ┆ A,NA,A,A,A ┆ … ┆ 0.00702937 ┆ 0.641545,N ┆ 0.004749  ┆ 0.004749  │
│       ┆            ┆          ┆            ┆   ┆ ,NA,0.0194 ┆ A,0.006068 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ 745,0.0240 ┆ 27,0.05191 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ …          ┆ …          ┆           ┆           │
│ 2     ┆ rs3018727  ┆ 61179006 ┆ T,T,T,T,T  ┆ … ┆ 0.00612812 ┆ 1.51913,0. ┆ 0.004572  ┆ 0.004572  │
│       ┆            ┆          ┆            ┆   ┆ ,0.0192098 ┆ 438955,0.1 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ ,0.0171149 ┆ 78608,0.03 ┆           ┆           │
│       ┆            ┆          ┆            ┆   ┆ …          ┆ …          ┆           ┆           │
└───────┴────────────┴──────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [25]:
snp

shape: (10_615, 14)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ BP       ┆ SNP       ┆ PIP(CS1)  ┆ LogBF(CS1 ┆ … ┆ LogBF(CS2 ┆ LogBF(CS2 ┆ LogBF(CS2 ┆ LogBF(CS2 │
│ ---      ┆ ---       ┆ ---       ┆ ,Pop1)    ┆   ┆ ,Pop2)    ┆ ,Pop3)    ┆ ,Pop4)    ┆ ,Pop5)    │
│ i64      ┆ str       ┆ f64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆           ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 61008633 ┆ rs5418602 ┆ 5.0052e-2 ┆ -0.495548 ┆ … ┆ -1.3958e- ┆ -4.3804e- ┆ -2.7533e- ┆ -2.8249e- │
│          ┆ 47        ┆ 0         ┆           ┆   ┆ 10        ┆ 10        ┆ 10        ┆ 11        │
│ 61013514 ┆ rs2006150 ┆ 3.1645e-2 ┆ -0.84742  ┆ … ┆ 1.28798   ┆ -1.02255  ┆ -2.7533e- ┆ -2.8249e- │
│          ┆ 31        ┆ 0         ┆           ┆   ┆           ┆           ┆ 10        ┆ 11        │
│ 61013552 ┆ rs5329716 ┆ 3.4240e-2 ┆ -0.875213 ┆ … ┆ -1.3958e- ┆ -4.3804e- ┆ -2.7533e- ┆ -2.8249e- │
│          ┆ 36        ┆ 0         ┆           ┆   ┆ 10        ┆ 10        ┆ 10        ┆ 11        │
│ 61014040 ┆ rs5614806 ┆ 1.0791e-1 ┆ -7.7104e- ┆ … ┆ -1.3958e- ┆ 1.12629   ┆ -2.7533e- ┆ -2.8249e- │
│          ┆ 1         ┆ 9         ┆ 11        ┆   ┆ 10        ┆           ┆ 10        ┆ 11        │
│ 61014431 ┆ rs1169897 ┆ 2.0063e-2 ┆ -7.7104e- ┆ … ┆ -1.42065  ┆ -4.3804e- ┆ -2.7533e- ┆ -2.8249e- │
│          ┆ 55        ┆ 0         ┆ 11        ┆   ┆           ┆ 10        ┆ 10        ┆ 11        │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 62999675 ┆ rs1387387 ┆ 1.5786e-2 ┆ -0.318016 ┆ … ┆ -1.3958e- ┆ -1.22859  ┆ -2.7533e- ┆ -2.8249e- │
│          ┆ 71        ┆ 0         ┆           ┆   ┆ 10        ┆           ┆ 10        ┆ 11        │
│ 62999828 ┆ rs1909447 ┆ 6.7261e-2 ┆ -1.23071  ┆ … ┆ -1.3958e- ┆ -1.32103  ┆ -2.7533e- ┆ -2.8249e- │
│          ┆ 38        ┆ 1         ┆           ┆   ┆ 10        ┆           ┆ 10        ┆ 11        │
│ 62999834 ┆ rs5593582 ┆ 5.9045e-2 ┆ -1.2354   ┆ … ┆ -1.3958e- ┆ 0.149376  ┆ -2.7533e- ┆ 0.937062  │
│          ┆ 0         ┆ 0         ┆           ┆   ┆ 10        ┆           ┆ 10        ┆           │
│ 62999844 ┆ rs5596203 ┆ 1.7977e-2 ┆ -1.23709  ┆ … ┆ -1.3958e- ┆ -0.803784 ┆ -2.7533e- ┆ 0.751308  │
│          ┆ 2         ┆ 0         ┆           ┆   ┆ 10        ┆           ┆ 10        ┆           │
│ 62999894 ┆ rs1385536 ┆ 5.2651e-2 ┆ -7.7104e- ┆ … ┆ -1.3958e- ┆ -0.577773 ┆ -2.7533e- ┆ -2.2501   │
│          ┆ 41        ┆ 1         ┆ 11        ┆   ┆ 10        ┆           ┆ 10        ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘