# Finemapping in srGWS data

In [9]:
!pip3 install polars

Requirement already satisfied: polars in /home/jupyter/.local/lib/python3.10/site-packages (1.37.1)
Requirement already satisfied: polars-runtime-32==1.37.1 in /home/jupyter/.local/lib/python3.10/site-packages (from polars) (1.37.1)

[notice] A new release of pip is available: 25.1 -> 25.3
[notice] To update, run: pip install --upgrade pip

## Data

In [ ]:
%%bash

# gcloud storage cp --billing-project=$GOOGLE_PROJECT *{tsv,parquet} $WORKSPACE_BUCKET/data/sumstats
gcloud storage cp --billing-project=$GOOGLE_PROJECT  $WORKSPACE_BUCKET/data/sumstats/*{tsv,parquet} .

gcloud storage cp --billing-project=$GOOGLE_PROJECT $WORKSPACE_BUCKET/data/srWGS/FADS/acaf_chr11_61000000-63000000.*

## Software

In [ ]:
%%bash

git clone https://github.com/omerwe/polyfun
cd polyfun

conda config --add pkgs_dirs ~/conda/pkgs
conda config --add envs_dirs ~/conda/envs
conda env create -f polyfun.yml

conda init
source ~/.bashrc
conda activate polyfun
cd ..

## SNPVAR

In [ ]:
%%bash

python polyfun/extract_snpvar.py --sumstats mdd2024_afr_hg38_z.parquet --out mdd2024_afr_hg38_snpvar.tsv

## Update map

Update variant IDs in LD reference to match sumstats.

In [3]:
import pandas as pd

In [22]:
bim = pd.read_csv("acaf_chr11_61000000-63000000.bim", sep = "\t", header = None, names = ["CHR", "ID", "CM", "BP", "A1", "A2"])

snpvar = pd.read_parquet("mdd2024_afr_hg38_snpvar.parquet")

In [37]:
snpvar["CPID_A1A2"] = (
    "chr" +
    snpvar["CHR"].astype(str) + ":" +
    snpvar["BP"].astype(str) + ":" +
    snpvar["A1"].astype(str) + ":" +
    snpvar["A2"].astype(str)
    
)
snpvar["CPID_A2A1"] = (
    "chr" +
    snpvar["CHR"].astype(str) + ":" +
    snpvar["BP"].astype(str) + ":" +
    snpvar["A2"].astype(str) + ":" +
    snpvar["A1"].astype(str)
    
)

In [39]:
bim_rsid_a1a2 = bim.merge(snpvar[["SNP", "CPID_A1A2"]], how = "left", left_on = "ID", right_on = "CPID_A1A2")
bim_rsid_a2a1 = bim.merge(snpvar[["SNP", "CPID_A2A1"]], how = "left", left_on = "ID", right_on = "CPID_A2A1")

In [50]:
map1 = bim_rsid_a1a2[bim_rsid_a1a2["SNP"].notna()][["ID", "SNP"]]
map2 = bim_rsid_a2a1[bim_rsid_a2a1["SNP"].notna()][["ID", "SNP"]]

In [51]:
map2

                       ID          SNP
21     chr11:61000492:C:T   rs12791045
23     chr11:61000546:T:A   rs12797044
24     chr11:61000572:G:A    rs2905517
56     chr11:61001264:C:T  rs117030061
58     chr11:61001373:T:A  rs141099168
...                   ...          ...
77363  chr11:62997317:C:T    rs3793960
77382  chr11:62998294:G:A  rs114687557
77392  chr11:62998731:C:T   rs72933455
77393  chr11:62998762:T:A   rs73492018
77398  chr11:62999198:G:A    rs3793961

[3557 rows x 2 columns]

In [55]:
maps = pd.concat([map1, map2]).drop_duplicates(subset = ["ID"], keep = "first")

In [59]:
maps.to_csv("cpid_rsid.map", header = None, index = None, sep = " ")

## Sample QC

In [77]:
!gsutil -u $GOOGLE_PROJECT cp gs://fc-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/relatedness/relatedness.tsv .
!gsutil -u $GOOGLE_PROJECT cp gs://fc-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/qc/flagged_samples.tsv .

Copying gs://fc-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/relatedness/relatedness.tsv...
/ [1 files][  1.0 MiB/  1.0 MiB]
Operation completed over 1 objects/1.0 MiB.
Copying gs://fc-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/qc/flagged_samples.tsv...
/ [1 files][538.5 KiB/538.5 KiB]
Operation completed over 1 objects/538.5 KiB.

In [10]:
relatedness = pd.read_csv("relatedness.tsv", sep = "\t")
flagged_samples = pd.read_csv("flagged_samples.tsv", sep = "\t")

In [11]:
relatedness_i = relatedness[["i.s"]].rename(columns = {"i.s" : "IID"})
relatedness_j = relatedness[["i.s"]].rename(columns = {"i.s" : "IID"})
flagged = flagged_samples[["s"]].rename(columns = {"s" : "IID"})

removed = (
    pd.concat([relatedness_i, relatedness_j, flagged])
    .drop_duplicates(subset = ["IID"])
    .assign(**{"#FID": 0})
    [["#FID", "IID"]]
)

removed.to_csv("flagged.ids", sep = "\t", index = None)

## Genetic clusters

In [61]:
!gsutil -u $GOOGLE_PROJECT cp gs://fc-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/ancestry/ancestry_preds.tsv .

Copying gs://fc-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/ancestry/ancestry_preds.tsv...
/ [1 files][163.4 MiB/163.4 MiB]
Operation completed over 1 objects/163.4 MiB.

In [2]:
ancestry_pred = pd.read_csv("ancestry_preds.tsv", sep = "\t")

In [3]:
(ancestry_pred
       .groupby('ancestry_pred', dropna=False)
       .size()
       .reset_index(name='n'))

  ancestry_pred       n
0           afr   84148
1           amr   79106
2           eas   10099
3           eur  234353
4           mid    1545
5           sas    5579

Randomly select up to 10,000 participants as a reference panel.

In [12]:
clust = (
    ancestry_pred
    [~ancestry_pred["research_id"].isin(removed["IID"])]
    .rename(columns = {'research_id': "IID"})
    .assign(**{"#FID": 0})
    .sample(frac = 1, random_state = 46779)
    .groupby("ancestry_pred", group_keys = False)
    .head(10000)
    .reset_index(drop = True)
    [["#FID", "IID", "ancestry_pred"]]
)

clust.to_csv("clusters.ids", sep = "\t", index = None)

In [13]:
(clust
       .groupby('ancestry_pred', dropna=False)
       .size()
       .reset_index(name='n')
)

  ancestry_pred      n
0           afr  10000
1           amr  10000
2           eas   9615
3           eur  10000
4           mid   1449
5           sas   5299

In [14]:
%%bash

for cluster in afr amr eas eur sas; do
    plink2 \
    --bfile acaf_chr11_61000000-63000000 \
    --make-bed \
    --update-name cpid_rsid.map \
    --keep-col-match clusters.ids ${cluster} \
    --keep-col-match-name ancestry_pred \
    --remove flagged.ids \
    --out acaf_chr11_61000000-63000000_${cluster}
done

PLINK v2.0.0-a.6.12LM 64-bit Intel (20 Apr 2025)   cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to acaf_chr11_61000000-63000000_afr.log.
Options in effect:
  --bfile acaf_chr11_61000000-63000000
  --keep-col-match clusters.ids afr
  --keep-col-match-name ancestry_pred
  --make-bed
  --out acaf_chr11_61000000-63000000_afr
  --remove flagged.ids
  --update-name cpid_rsid.map

Start time: Wed Jan 28 16:02:35 2026
14993 MiB RAM detected, ~13522 available; reserving 7496 MiB for main
workspace.
Using up to 4 compute threads.
414830 samples (0 females, 0 males, 414830 ambiguous; 414830 founders) loaded
from acaf_chr11_61000000-63000000.fam.
77403 variants loaded from acaf_chr11_61000000-63000000.bim.
Note: No phenotype data present.
--update-name: 6052 values updated.
--remove: 381254 samples remaining.
--keep-col-match: 10000 samples remaining.
10000 samples (0 females, 0 males, 10000 ambiguous; 10000 founders) remaining
after main filters.
Writing acaf_chr11_61000000-63000000_afr.fam ... done.
Writing acaf_chr11_61000000-63000000_afr.bim ... done.
Writing acaf_chr11_61000000-63000000_afr.bed ... 21426384done.
End time: Wed Jan 28 16:02:47 2026
PLINK v2.0.0-a.6.12LM 64-bit Intel (20 Apr 2025)   cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to acaf_chr11_61000000-63000000_amr.log.
Options in effect:
  --bfile acaf_chr11_61000000-63000000
  --keep-col-match clusters.ids amr
  --keep-col-match-name ancestry_pred
  --make-bed
  --out acaf_chr11_61000000-63000000_amr
  --remove flagged.ids
  --update-name cpid_rsid.map

Start time: Wed Jan 28 16:02:47 2026
14993 MiB RAM detected, ~13531 available; reserving 7496 MiB for main
workspace.
Using up to 4 compute threads.
414830 samples (0 females, 0 males, 414830 ambiguous; 414830 founders) loaded
from acaf_chr11_61000000-63000000.fam.
77403 variants loaded from acaf_chr11_61000000-63000000.bim.
Note: No phenotype data present.
--update-name: 6052 values updated.
--remove: 381254 samples remaining.
--keep-col-match: 10000 samples remaining.
10000 samples (0 females, 0 males, 10000 ambiguous; 10000 founders) remaining
after main filters.
Writing acaf_chr11_61000000-63000000_amr.fam ... done.
Writing acaf_chr11_61000000-63000000_amr.bim ... done.
Writing acaf_chr11_61000000-63000000_amr.bed ... 21426384done.
End time: Wed Jan 28 16:02:59 2026
PLINK v2.0.0-a.6.12LM 64-bit Intel (20 Apr 2025)   cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to acaf_chr11_61000000-63000000_eas.log.
Options in effect:
  --bfile acaf_chr11_61000000-63000000
  --keep-col-match clusters.ids eas
  --keep-col-match-name ancestry_pred
  --make-bed
  --out acaf_chr11_61000000-63000000_eas
  --remove flagged.ids
  --update-name cpid_rsid.map

Start time: Wed Jan 28 16:02:59 2026
14993 MiB RAM detected, ~13526 available; reserving 7496 MiB for main
workspace.
Using up to 4 compute threads.
414830 samples (0 females, 0 males, 414830 ambiguous; 414830 founders) loaded
from acaf_chr11_61000000-63000000.fam.
77403 variants loaded from acaf_chr11_61000000-63000000.bim.
Note: No phenotype data present.
--update-name: 6052 values updated.
--remove: 381254 samples remaining.
--keep-col-match: 9615 samples remaining.
9615 samples (0 females, 0 males, 9615 ambiguous; 9615 founders) remaining
after main filters.
Writing acaf_chr11_61000000-63000000_eas.fam ... done.
Writing acaf_chr11_61000000-63000000_eas.bim ... done.
Writing acaf_chr11_61000000-63000000_eas.bed ... 21426384done.
End time: Wed Jan 28 16:03:11 2026
PLINK v2.0.0-a.6.12LM 64-bit Intel (20 Apr 2025)   cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to acaf_chr11_61000000-63000000_eur.log.
Options in effect:
  --bfile acaf_chr11_61000000-63000000
  --keep-col-match clusters.ids eur
  --keep-col-match-name ancestry_pred
  --make-bed
  --out acaf_chr11_61000000-63000000_eur
  --remove flagged.ids
  --update-name cpid_rsid.map

Start time: Wed Jan 28 16:03:11 2026
14993 MiB RAM detected, ~13517 available; reserving 7496 MiB for main
workspace.
Using up to 4 compute threads.
414830 samples (0 females, 0 males, 414830 ambiguous; 414830 founders) loaded
from acaf_chr11_61000000-63000000.fam.
77403 variants loaded from acaf_chr11_61000000-63000000.bim.
Note: No phenotype data present.
--update-name: 6052 values updated.
--remove: 381254 samples remaining.
--keep-col-match: 10000 samples remaining.
10000 samples (0 females, 0 males, 10000 ambiguous; 10000 founders) remaining
after main filters.
Writing acaf_chr11_61000000-63000000_eur.fam ... done.
Writing acaf_chr11_61000000-63000000_eur.bim ... done.
Writing acaf_chr11_61000000-63000000_eur.bed ... 21426384done.
End time: Wed Jan 28 16:03:23 2026
PLINK v2.0.0-a.6.12LM 64-bit Intel (20 Apr 2025)   cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to acaf_chr11_61000000-63000000_sas.log.
Options in effect:
  --bfile acaf_chr11_61000000-63000000
  --keep-col-match clusters.ids sas
  --keep-col-match-name ancestry_pred
  --make-bed
  --out acaf_chr11_61000000-63000000_sas
  --remove flagged.ids
  --update-name cpid_rsid.map

Start time: Wed Jan 28 16:03:23 2026
14993 MiB RAM detected, ~13539 available; reserving 7496 MiB for main
workspace.
Using up to 4 compute threads.
414830 samples (0 females, 0 males, 414830 ambiguous; 414830 founders) loaded
from acaf_chr11_61000000-63000000.fam.
77403 variants loaded from acaf_chr11_61000000-63000000.bim.
Note: No phenotype data present.
--update-name: 6052 values updated.
--remove: 381254 samples remaining.
--keep-col-match: 5299 samples remaining.
5299 samples (0 females, 0 males, 5299 ambiguous; 5299 founders) remaining
after main filters.
Writing acaf_chr11_61000000-63000000_sas.fam ... done.
Writing acaf_chr11_61000000-63000000_sas.bim ... done.
Writing acaf_chr11_61000000-63000000_sas.bed ... 21426384done.
End time: Wed Jan 28 16:03:31 2026

# Finemapping

In [100]:
!git clone https://github.com/getian107/SuSiEx.git
!chmod a+x SuSiEx/bin_static/SuSiEx

Cloning into 'SuSiEx'...
remote: Enumerating objects: 359, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 359 (delta 52), reused 63 (delta 23), pack-reused 249 (from 1)
Receiving objects: 100% (359/359), 37.42 MiB | 20.24 MiB/s, done.
Resolving deltas: 100% (212/212), done.

In [ ]:
%%bash

sumstats_afr=mdd2024_afr_hg38_susie.tsv
sumstats_amr=mdd2024_his_hg38_susie.tsv
sumstats_eas=mdd2024_eas_hg38_susie.tsv
sumstats_eur=mdd2025_eur_hg38_susie.tsv
sumstats_sas=mdd2024_sas_hg38_susie.tsv

ref_afr=acaf_chr11_61000000-63000000_afr
ref_amr=acaf_chr11_61000000-63000000_amr
ref_eas=acaf_chr11_61000000-63000000_eas
ref_eur=acaf_chr11_61000000-63000000_eur
ref_sas=acaf_chr11_61000000-63000000_sas

ld_afr=ld/acaf_chr11_61000000-63000000_afr
ld_amr=ld/acaf_chr11_61000000-63000000_amr
ld_eas=ld/acaf_chr11_61000000-63000000_eas
ld_eur=ld/acaf_chr11_61000000-63000000_eur
ld_sas=ld/acaf_chr11_61000000-63000000_sas

mkdir -p ld

./SuSiEx/bin_static/SuSiEx \
  --sst_file=$sumstats_afr,$sumstats_eas,$sumstats_amr,$sumstats_sas,$sumstats_eur \
  --n_gwas=70727,58319,16211,14979,1577200 \
  --ref_file=$ref_afr,$ref_eas,$ref_amr,$ref_sas,$ref_eur \
  --ld_file=$ld_afr,$ld_eas,$ld_amr,$ld_sas,$ld_eur \
  --out_dir=. \
  --out_name=mdd_acaf_hg38_chr11_61600000-62000000 \
  --chr=11 \
  --bp=61600000,62000000 \
  --chr_col=1,1,1,1,1 \
  --snp_col=2,2,2,2,2 \
  --bp_col=3,3,3,3,3 \
  --a1_col=4,4,4,4,4 \
  --a2_col=5,5,5,5,5 \
  --eff_col=6,6,6,6,6 \
  --se_col=7,7,7,7,7 \
  --pval_col=8,8,8,8,8 \
  --plink=/usr/bin/plink \
  --keep-ambig=True \
  --maf=0.005 \
  --mult-step=True \
  --pval_thresh=1e-5 \
  --max_iter=500 \
  --tol=1e-4 \
  --threads=30

Software parameters:
--sst_file = mdd2024_afr_hg38_snpvar.tsv,mdd2024_eas_hg38_snpvar.tsv,,mdd2024_sas_hg38_snpvar.tsv,mdd2024_eur_hg38_snpvar.tsv
--ref_file = acaf_chr11_61000000-63000000_afr,acaf_chr11_61000000-63000000_eas,acaf_chr11_61000000-63000000_amr,acaf_chr11_61000000-63000000_sas,acaf_chr11_61000000-63000000_eur
--ld_file = ld/acaf_chr11_61000000-63000000_afr,ld/acaf_chr11_61000000-63000000_eas,ld/acaf_chr11_61000000-63000000_amr,ld/acaf_chr11_61000000-63000000_sas,ld/acaf_chr11_61000000-63000000_eur
--n_gwas = 70727,58319,16211,14979,1577200
--out_dir = .
--out_name = mdd_acaf_hg38_chr11_61000000-63000000
--chr = 11
--bp = 61000000,63000000
--chr_col = 1,1,1,1,1
--snp_col = 2,2,2,2,2
--bp_col = 3,3,3,3,3
--a1_col = 4,4,4,4,4
--a2_col = 5,5,5,5,5
--eff_col = 6,6,6,6,6
--se_col = 7,7,7,7,7
--pval_col = 8,8,8,8,8
--plink = /usr/bin/plink
--keep-ambig = true
--mult-step = true
--precmp = false
--maf = 0.005
--level = 0.95
--min_purity = 0.5
--pval_thresh = 1e-05
--tol = 0.0001
--n_sig = 5
--max_iter = 500
--threads = 4
... calculate LD matrix: ld/acaf_chr11_61000000-63000000_afr.ld ...
PLINK v1.90b6.22 64-bit (16 Apr 2021)          www.cog-genomics.org/plink/1.9/
(C) 2005-2021 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to ld/acaf_chr11_61000000-63000000_afr_ref.log.
Options in effect:
  --bfile acaf_chr11_61000000-63000000_afr
  --chr 11
  --extract ld/acaf_chr11_61000000-63000000_afr.snp
  --keep-allele-order
  --maf 0.005
  --make-bed
  --out ld/acaf_chr11_61000000-63000000_afr_ref

14993 MB RAM detected; reserving 7496 MB for main workspace.
77403 variants loaded from .bim file.
73468 people (0 males, 0 females, 73468 ambiguous) loaded from .fam.
Ambiguous sex IDs written to ld/acaf_chr11_61000000-63000000_afr_ref.nosex .
--extract: 77403 variants remaining.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 73468 founders and 0 nonfounders present.
Calculating allele frequencies... 10111213141516171819202122232425262728293031323334353637383940414243444546474849505152535455565758596061626364656667686970717273747576777879808182838485868788899091929394959697989 done.
Total genotyping rate is 0.838306.
61270 variants removed due to minor allele threshold(s)
(--maf/--max-maf/--mac/--max-mac).
16133 variants and 73468 people pass filters and QC.
Note: No phenotypes present.
--make-bed to ld/acaf_chr11_61000000-63000000_afr_ref.bed +
ld/acaf_chr11_61000000-63000000_afr_ref.bim +
ld/acaf_chr11_61000000-63000000_afr_ref.fam ... 101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899done.
PLINK v1.90b6.22 64-bit (16 Apr 2021)          www.cog-genomics.org/plink/1.9/
(C) 2005-2021 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to ld/acaf_chr11_61000000-63000000_afr.log.
Options in effect:
  --bfile ld/acaf_chr11_61000000-63000000_afr_ref
  --keep-allele-order
  --out ld/acaf_chr11_61000000-63000000_afr
  --r square bin4

14993 MB RAM detected; reserving 7496 MB for main workspace.
16133 variants loaded from .bim file.
73468 people (0 males, 0 females, 73468 ambiguous) loaded from .fam.
Ambiguous sex IDs written to ld/acaf_chr11_61000000-63000000_afr.nosex .
Using up to 4 threads (change this with --threads).
Before main variant filters, 73468 founders and 0 nonfounders present.
Calculating allele frequencies... 10111213141516171819202122232425262728293031323334353637383940414243444546474849505152535455565758596061626364656667686970717273747576777879808182838485868788899091929394959697989 done.
Total genotyping rate is 0.888777.
16133 variants and 73468 people pass filters and QC.
Note: No phenotypes present.
--r square bin4 to ld/acaf_chr11_61000000-63000000_afr.ld.bin ...
Error while terminating subprocess (pid=1690):
0% [processing]PLINK v1.90b6.22 64-bit (16 Apr 2021)          www.cog-genomics.org/plink/1.9/
(C) 2005-2021 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to ld/acaf_chr11_61000000-63000000_afr_frq.log.
Options in effect:
  --bfile ld/acaf_chr11_61000000-63000000_afr_ref
  --freq
  --keep-allele-order
  --out ld/acaf_chr11_61000000-63000000_afr_frq

14993 MB RAM detected; reserving 7496 MB for main workspace.
16133 variants loaded from .bim file.
73468 people (0 males, 0 females, 73468 ambiguous) loaded from .fam.
Ambiguous sex IDs written to ld/acaf_chr11_61000000-63000000_afr_frq.nosex .
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 73468 founders and 0 nonfounders present.
Calculating allele frequencies... 10111213141516171819202122232425262728293031323334353637383940414243444546474849505152535455565758596061626364656667686970717273747576777879808182838485868788899091929394959697989 done.
Total genotyping rate is 0.888777.
--freq: Allele frequencies (founders only) written to
ld/acaf_chr11_61000000-63000000_afr_frq.frq .
... calculate LD matrix: ld/acaf_chr11_61000000-63000000_eas.ld ...
PLINK v1.90b6.22 64-bit (16 Apr 2021)          www.cog-genomics.org/plink/1.9/
(C) 2005-2021 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to ld/acaf_chr11_61000000-63000000_eas_ref.log.
Options in effect:
  --bfile acaf_chr11_61000000-63000000_eas
  --chr 11
  --extract ld/acaf_chr11_61000000-63000000_eas.snp
  --keep-allele-order
  --maf 0.005
  --make-bed
  --out ld/acaf_chr11_61000000-63000000_eas_ref

14993 MB RAM detected; reserving 7496 MB for main workspace.
77403 variants loaded from .bim file.
9615 people (0 males, 0 females, 9615 ambiguous) loaded from .fam.
Ambiguous sex IDs written to ld/acaf_chr11_61000000-63000000_eas_ref.nosex .
--extract: 77403 variants remaining.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 9615 founders and 0 nonfounders present.
Calculating allele frequencies... 10111213141516171819202122232425262728293031323334353637383940414243444546474849505152535455565758596061626364656667686970717273747576777879808182838485868788899091929394959697989 done.
Total genotyping rate is 0.828752.
68417 variants removed due to minor allele threshold(s)
(--maf/--max-maf/--mac/--max-mac).
8986 variants and 9615 people pass filters and QC.
Note: No phenotypes present.
--make-bed to ld/acaf_chr11_61000000-63000000_eas_ref.bed +
ld/acaf_chr11_61000000-63000000_eas_ref.bim +
ld/acaf_chr11_61000000-63000000_eas_ref.fam ... 101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899done.
PLINK v1.90b6.22 64-bit (16 Apr 2021)          www.cog-genomics.org/plink/1.9/
(C) 2005-2021 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to ld/acaf_chr11_61000000-63000000_eas.log.
Options in effect:
  --bfile ld/acaf_chr11_61000000-63000000_eas_ref
  --keep-allele-order
  --out ld/acaf_chr11_61000000-63000000_eas
  --r square bin4

14993 MB RAM detected; reserving 7496 MB for main workspace.
8986 variants loaded from .bim file.
9615 people (0 males, 0 females, 9615 ambiguous) loaded from .fam.
Ambiguous sex IDs written to ld/acaf_chr11_61000000-63000000_eas.nosex .
Using up to 4 threads (change this with --threads).
Before main variant filters, 9615 founders and 0 nonfounders present.
Calculating allele frequencies... 10111213141516171819202122232425262728293031323334353637383940414243444546474849505152535455565758596061626364656667686970717273747576777879808182838485868788899091929394959697989 done.
Total genotyping rate is 0.79619.
8986 variants and 9615 people pass filters and QC.
Note: No phenotypes present.
--r square bin4 to ld/acaf_chr11_61000000-63000000_eas.ld.bin ...
0% [processingwriting]          done.
PLINK v1.90b6.22 64-bit (16 Apr 2021)          www.cog-genomics.org/plink/1.9/
(C) 2005-2021 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to ld/acaf_chr11_61000000-63000000_eas_frq.log.
Options in effect:
  --bfile ld/acaf_chr11_61000000-63000000_eas_ref
  --freq
  --keep-allele-order
  --out ld/acaf_chr11_61000000-63000000_eas_frq

14993 MB RAM detected; reserving 7496 MB for main workspace.

Error: Failed to open ld/acaf_chr11_61000000-63000000_eas_ref.bed.
rm: cannot remove 'ld/acaf_chr11_61000000-63000000_eas.snp': No such file or directory
rm: cannot remove 'ld/acaf_chr11_61000000-63000000_eas_ref.bed': No such file or directory
rm: cannot remove 'ld/acaf_chr11_61000000-63000000_eas_ref.fam': No such file or directory
rm: cannot remove 'ld/acaf_chr11_61000000-63000000_eas_ref.log': No such file or directory
rm: cannot remove 'ld/acaf_chr11_61000000-63000000_eas.log': No such file or directory

... calculate LD matrix: ld/acaf_chr11_61000000-63000000_amr.ld ...
PLINK v1.90b6.22 64-bit (16 Apr 2021)          www.cog-genomics.org/plink/1.9/
(C) 2005-2021 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to ld/acaf_chr11_61000000-63000000_amr_ref.log.
Options in effect:
  --bfile acaf_chr11_61000000-63000000_amr
  --chr 11
  --extract ld/acaf_chr11_61000000-63000000_amr.snp
  --keep-allele-order
  --maf 0.005
  --make-bed
  --out ld/acaf_chr11_61000000-63000000_amr_ref

14993 MB RAM detected; reserving 7496 MB for main workspace.
77403 variants loaded from .bim file.
69801 people (0 males, 0 females, 69801 ambiguous) loaded from .fam.
Ambiguous sex IDs written to ld/acaf_chr11_61000000-63000000_amr_ref.nosex .
--extract: 77403 variants remaining.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 69801 founders and 0 nonfounders present.
Calculating allele frequencies... 10111213141516171819202122232425262728293031323334353637383940414243444546474849505152535455565758596061626364656667686970717273747576777879808182838485868788899091929394959697989 done.
Total genotyping rate is 0.831186.
65726 variants removed due to minor allele threshold(s)
(--maf/--max-maf/--mac/--max-mac).
11677 variants and 69801 people pass filters and QC.
Note: No phenotypes present.
--make-bed to ld/acaf_chr11_61000000-63000000_amr_ref.bed +
ld/acaf_chr11_61000000-63000000_amr_ref.bim +
ld/acaf_chr11_61000000-63000000_amr_ref.fam ... 101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899done.
PLINK v1.90b6.22 64-bit (16 Apr 2021)          www.cog-genomics.org/plink/1.9/
(C) 2005-2021 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to ld/acaf_chr11_61000000-63000000_amr.log.
Options in effect:
  --bfile ld/acaf_chr11_61000000-63000000_amr_ref
  --keep-allele-order
  --out ld/acaf_chr11_61000000-63000000_amr
  --r square bin4

14993 MB RAM detected; reserving 7496 MB for main workspace.
11677 variants loaded from .bim file.
69801 people (0 males, 0 females, 69801 ambiguous) loaded from .fam.
Ambiguous sex IDs written to ld/acaf_chr11_61000000-63000000_amr.nosex .
Using up to 4 threads (change this with --threads).
Before main variant filters, 69801 founders and 0 nonfounders present.
Calculating allele frequencies... 10111213141516171819202122232425262728293031323334353637383940414243444546474849505152535455565758596061626364656667686970717273747576777879808182838485868788899091929394959697989 done.
Total genotyping rate is 0.843493.
11677 variants and 69801 people pass filters and QC.
Note: No phenotypes present.
--r square bin4 to ld/acaf_chr11_61000000-63000000_amr.ld.bin ...

In [6]:
cs = pd.read_csv("mdd_acaf_hg38_chr11_61000000-63000000.cs", sep="\t")
snp = pd.read_csv("mdd_acaf_hg38_chr11_61000000-63000000.snp", sep="\t")
summary = pd.read_csv("mdd_acaf_hg38_chr11_61000000-63000000.summary", sep="\t", comment="#")

In [7]:
summary

,CS_ID,CS_LENGTH,CS_PURITY,MAX_PIP_SNP,BP,REF_ALLELE,ALT_ALLELE,REF_FRQ,BETA,SE,-LOG10P,MAX_PIP,POST-HOC_PROB_POP1,POST-HOC_PROB_POP2,POST-HOC_PROB_POP3,POST-HOC_PROB_POP4,POST-HOC_PROB_POP5
0,1,5,0.996141,rs28456,61822009,"A,A,A,A,A","G,G,G,G,G","0.8453,0.3975,0.4564,0.7794,0.7028","-0.0186391,-0.00859807,0.0225219,-0.0148914,-0...","0.00735261,0.00598319,0.0111498,0.0139335,0.00...","1.94909,0.821865,1.36261,0.544877,20.2658",0.398564,0.620173,0.323584,0.618600,0.344088,1.000000
1,2,50,0.706765,rs2957859,61483598,"G,NA,G,NA,G","T,NA,T,NA,T","0.0388,NA,0.0782,NA,0.1273","-0.00933789,NA,-0.0194775,NA,-0.0109132","0.013768,NA,0.0206851,NA,0.00168925","0.303099,NA,0.460438,NA,9.98115",0.072821,0.588716,0.301242,0.341665,0.302463,0.999996

In [8]:
cs

,CS_ID,SNP,BP,REF_ALLELE,ALT_ALLELE,REF_FRQ,BETA,SE,-LOG10P,CS_PIP,OVRL_PIP
0,1,rs28456,61822009,"A,A,A,A,A","G,G,G,G,G","0.8453,0.3975,0.4564,0.7794,0.7028","-0.0186391,-0.00859807,0.0225219,-0.0148914,-0...","0.00735261,0.00598319,0.0111498,0.0139335,0.00...","1.94909,0.821865,1.36261,0.544877,20.2658",0.398564,0.398564
1,1,rs174548,61803876,"C,C,C,C,C","G,G,G,G,G","0.7894,0.3984,0.4452,0.7785,0.7025","-0.0153915,-0.00811976,0.0224246,-0.0144784,-0...","0.00652101,0.0059809,0.0111747,0.0139132,0.001...","1.73849,0.757992,1.34894,0.525711,20.4274",0.349324,0.349324
2,1,rs174560,61814292,"T,T,T,T,T","C,C,C,C,C","0.79,0.3983,0.4452,0.7786,0.704","-0.0149616,-0.00780322,0.0222741,-0.0142633,-0...","0.00652784,0.00598115,0.0111747,0.0139155,0.00...","1.65941,0.716661,1.33505,0.515183,19.9286",0.107933,0.107933
3,1,rs174549,61803910,"G,G,G,G,G","A,A,A,A,A","0.92559,0.3985,0.4738,0.7817,0.7087","-0.0155347,-0.00772335,0.0224972,-0.0147409,-0...","0.0101314,0.00598064,0.0111226,0.0139861,0.001...","0.902417,0.706487,1.36543,0.53477,20.2658",0.073504,0.073504
4,1,rs174544,61800281,"C,C,C,C,C","A,A,A,A,A","0.92578,0.3991,0.4741,0.782,0.7115","-0.0159587,-0.0076422,0.0206248,-0.0129935,-0....","0.0101433,0.00597913,0.0111223,0.013993,0.0012...","0.936886,0.696376,1.19595,0.452088,19.769",0.022428,0.022428
5,2,rs2957859,61483598,"G,NA,G,NA,G","T,NA,T,NA,T","0.0388,NA,0.0782,NA,0.1273","-0.00933789,NA,-0.0194775,NA,-0.0109132","0.013768,NA,0.0206851,NA,0.00168925","0.303099,NA,0.460438,NA,9.98115",0.072821,0.072821
6,2,rs112830700,61366508,"G,NA,G,NA,G","A,NA,A,NA,A","0.9773,NA,0.92489,NA,0.8749","-0.00530825,NA,0.028198,NA,0.0108386","0.0178511,NA,0.021071,NA,0.0017019","0.115663,NA,0.742754,NA,9.71936",0.060030,0.060030
7,2,rs3741265,61397808,"G,G,G,G,G","A,A,A,A,A","0.2387,0.0381,0.121,0.119,0.1416","-0.0132821,0.0139687,-0.00675831,0.00209365,-0...","0.00623718,0.0152951,0.0170292,0.0178436,0.001...","1.47869,0.442378,0.160229,0.0425862,10.2629",0.052872,0.052872
8,2,rs2924443,61466040,"G,G,G,G,G","A,A,A,A,A","0.2395,0.0384,0.1225,0.1228,0.1401","-0.0150596,0.0146165,-0.00560117,0.00501601,-0...","0.00623003,0.0152376,0.016939,0.0176033,0.0016...","1.80583,0.471806,0.130243,0.110314,9.97475",0.045483,0.045483
9,2,rs896832,61437167,"A,A,A,A,A","G,G,G,G,G","0.2252,0.0381,0.1202,0.1193,0.14","-0.0152942,0.0126423,-0.0114298,0.0017203,-0.0...","0.00636522,0.0152951,0.017078,0.0178242,0.0016...","1.78858,0.388821,0.298153,0.0347457,9.8078",0.038666,0.038666
10,2,rs7925113,61394401,"A,A,A,A,A","G,G,G,G,G","0.2087,0.011,0.1186,0.1154,0.1414","-0.014878,0.0448492,-0.00588805,-0.00222486,-0...","0.00654275,0.0280728,0.0171772,0.0180829,0.001...","1.63888,0.95809,0.135631,0.0447559,9.65057",0.038091,0.038091
11,2,rs2860196,61432192,"G,G,G,G,G","A,A,A,A,A","0.2103,0.0381,0.1189,0.1195,0.14","-0.0156057,0.0133055,-0.00635661,0.00118426,-0...","0.00652442,0.0152951,0.0171584,0.0178113,0.001...","1.77568,0.415279,0.148109,0.0236554,9.89109",0.037653,0.037653
12,2,rs7934229,61441661,"T,T,T,T,T","C,C,C,C,C","0.2278,0.0381,0.1204,0.1194,0.14","-0.0148068,0.0129739,-0.0111105,0.00171967,-0....","0.00633944,0.0152951,0.0170657,0.0178177,0.001...","1.70977,0.40197,0.288176,0.0347457,9.8078",0.033876,0.033876
13,2,rs2943806,61435440,"T,T,T,T,T","C,C,C,C,C","0.2278,0.0381,0.1204,0.1193,0.14","-0.014836,0.0129739,-0.0109327,0.00152506,-0.0...","0.00633944,0.0152951,0.0170657,0.0178242,0.001...","1.71513,0.40197,0.282524,0.0306703,9.8078",0.033726,0.033726
14,2,rs17702,61446448,"T,T,T,T,T","C,C,C,C,C","0.2277,0.0381,0.1204,0.1194,0.1399","-0.0146761,0.0127666,-0.0115105,0.00210747,-0....","0.00634042,0.0152951,0.0170657,0.0178177,0.001...","1.6855,0.393733,0.301024,0.0429456,9.8078",0.033385,0.033385
15,2,rs896831,61436889,"A,A,A,A,A","C,C,C,C,C","0.21,0.0381,0.1189,0.1193,0.14","-0.0157903,0.0130153,-0.00671222,0.001521,-0.0...","0.00652784,0.0152951,0.0171584,0.0178242,0.001...","1.8078,0.403625,0.157606,0.0305858,9.8078",0.033015,0.033015
16,2,rs3018726,61431256,"A,A,A,A,A","C,C,C,C,C","0.2277,0.0381,0.1198,0.1195,0.1396","-0.0147503,0.0130153,-0.0120566,0.00166683,-0....","0.00634042,0.0152951,0.0171026,0.0178113,0.001...","1.69902,0.403625,0.318004,0.0336515,9.8078",0.032937,0.032937
17,2,rs896829,61473908,"T,T,T,T,T","C,C,C,C,C","0.252,0.0371,0.1234,0.1235,0.14","-0.0158956,0.0141556,-0.00456373,0.00631993,-0...","0.00612409,0.0154918,0.0168858,0.0175604,0.001...","2.02489,0.442673,0.104052,0.143317,9.65057",0.032372,0.032372
18,2,rs4939521,61399637,"A,NA,A,NA,A","G,NA,G,NA,G","0.1359,NA,0.088,NA,0.1314","-0.014864,NA,-0.00539518,NA,-0.0102796","0.00775891,NA,0.0196038,NA,0.00166661","1.25649,NA,0.106152,NA,9.16008",0.026063,0.026063
19,2,rs2924435,61451504,"A,A,A,A,A","G,G,G,G,G","0.2272,0.0381,0.12,0.1192,0.1397","-0.0149093,0.0128495,-0.00724086,0.00206107,-0...","0.00634534,0.0152951,0.0170902,0.0178306,0.001...","1.72605,0.397021,0.172763,0.0419254,9.72488",0.025265,0.025265
20,2,rs2277285,61429516,"T,T,T,T,T","G,G,G,G,G","0.2098,0.0383,0.1188,0.1193,0.1399","-0.0153392,0.013024,-0.00793586,0.00137474,-0....","0.00653012,0.0152567,0.0171646,0.0178242,0.001...","1.72528,0.405282,0.191223,0.0275555,9.72488",0.024891,0.024891
21,2,rs6591655,61451793,"G,G,G,G,G","A,A,A,A,A","0.228,0.0382,0.1204,0.1194,0.14","-0.0149352,0.0127506,-0.00709574,0.00205957,-0...","0.00633748,0.0152759,0.0170657,0.0178177,0.001...","1.73422,0.393733,0.16905,0.0419254,9.72488",0.024342,0.024342
22,2,rs35605696,61463705,"A,A,A,A,A","G,G,G,G,G","0.2613,0.0384,0.1246,0.1194,0.1401","-0.0137382,0.0143681,-0.00926218,0.00340069,-0...","0.00605186,0.0152376,0.0168158,0.0178177,0.001...","1.63445,0.461283,0.235249,0.071279,9.72488",0.022427,0.022427
23,2,rs2924446,61493410,"C,NA,C,C,C","T,NA,T,T,T","0.1814,NA,0.0944,0.062,0.1341","-0.0101111,NA,-0.00340819,0.00805085,-0.0104168","0.00689982,NA,0.0189944,0.0239578,0.00165232","0.845243,NA,0.0667156,0.132628,9.53845",0.021808,0.021808
24,2,rs730338,61474751,"T,T,T,T,T","C,C,C,C,C","0.2622,0.0372,0.1256,0.129,0.1402","-0.0140753,0.0135535,-0.00646154,0.00634075,-0...","0.00604514,0.0154718,0.0167583,0.0172361,0.001...","1.7013,0.419047,0.155018,0.146931,9.56835",0.015421,0.015421
25,2,rs3018732,61479386,"T,T,T,T,T","C,C,C,C,C","0.2656,0.0381,0.1234,0.1205,0.1332","-0.0127647,0.0146767,-0.0188502,0.00321735,-0....","0.00602022,0.0152951,0.0168858,0.0177473,0.001...","1.46877,0.472019,0.577939,0.0674539,9.46689",0.015199,0.015199
26,2,rs35723406,61343874,"C,NA,C,NA,C","G,NA,G,NA,G","0.9775,NA,0.92175,NA,0.876","-0.014008,NA,0.0257717,NA,0.0105667","0.0179284,NA,0.0206791,NA,0.00170836","0.3619,NA,0.672302,NA,9.20767",0.015108,0.015108
27,2,rs921635,61405864,"C,C,C,C,C","T,T,T,T,T","0.2408,0.0381,0.1214,0.119,0.1416","-0.012616,0.0139687,-0.00814635,0.00214123,-0....","0.00621851,0.0152951,0.0170049,0.0178436,0.001...","1.37181,0.442378,0.199353,0.0435995,9.72488",0.014124,0.014124
28,2,rs112167183,61464815,"C,NA,C,NA,C","T,NA,T,NA,T","0.97522,NA,0.92386,NA,0.8709","0.00514813,NA,0.0277764,NA,0.0102582","0.0171037,NA,0.0209397,NA,0.00167917","0.117237,NA,0.733588,NA,8.99906",0.012286,0.012286
29,2,rs2924442,61478480,"A,A,A,A,A","G,G,G,G,G","0.2657,0.0376,0.1233,0.1206,0.1331","-0.0126274,0.0146872,-0.01639,0.00154568,-0.01...","0.00601949,0.0153925,0.0168917,0.0177409,0.001...","1.44457,0.468529,0.478995,0.0312499,9.46689",0.011718,0.011718
30,2,rs2943800,61478142,"G,G,G,G,G","T,T,T,T,T","0.265,0.0378,0.1234,0.1212,0.1334","-0.0128192,0.014567,-0.0152975,0.0020016,-0.01...","0.00602457,0.0153533,0.0168858,0.017703,0.0016...","1.47688,0.465049,0.437746,0.0409687,9.46689",0.011685,0.011685
31,2,rs1037448,61367060,"T,T,T,T,T","C,C,C,C,C","0.5977,0.0171,0.1422,0.1355,0.1352","-0.00733082,0.00533131,-0.0193953,0.00947197,-...","0.0054222,0.0225854,0.0159015,0.0168807,0.0016...","0.753562,0.0896997,0.65253,0.240542,9.53845",0.011633,0.011633
32,2,rs28720282,61323484,"T,NA,T,NA,T","C,NA,C,NA,C","0.97749,NA,0.92171,NA,0.8759","-0.0172352,NA,0.0248014,NA,0.010471","0.0179246,NA,0.0206743,NA,0.00170777","0.473297,NA,0.637736,NA,9.05995",0.011422,0.011422
33,2,rs7607,61398834,"G,G,G,G,G","A,A,A,A,A","0.6332,0.0463,0.1711,0.1513,0.1532","-0.00609546,0.01035,-0.0170827,0.0180226,-0.00...","0.00551705,0.0139342,0.014747,0.016123,0.00156323","0.569877,0.339497,0.607819,0.57898,9.61722",0.010867,0.010867
34,2,rs2957860,61478471,"G,NA,G,NA,G","A,NA,A,NA,A","0.0392,NA,0.0786,NA,0.1296","-0.00428662,NA,-0.0192792,NA,-0.0103293","0.0137004,NA,0.0206369,NA,0.00167641","0.122416,NA,0.45569,NA,9.14258",0.010253,0.010253
35,2,rs3019199,61409333,"G,G,G,G,G","A,A,A,A,A","0.6332,0.0462,0.1711,0.1521,0.1532","-0.00613995,0.0110079,-0.0172738,0.0180411,-0....","0.00551705,0.0139486,0.014747,0.0160882,0.0015...","0.575527,0.366521,0.617151,0.581495,9.53898",0.009598,0.009598
36,2,rs3019198,61411813,"G,G,G,G,G","A,A,A,A,A","0.6335,0.0462,0.1712,0.1512,0.1532","-0.00605201,0.0108886,-0.0171245,0.0180385,-0....","0.005518,0.0139486,0.0147436,0.0161274,0.00156323","0.564251,0.361489,0.61005,0.579459,9.53898",0.009409,0.009409
37,2,rs2943805,61439838,"T,T,T,T,T","G,G,G,G,G","0.2297,0.0385,0.1252,0.1279,0.1489","-0.0146752,0.0131922,-0.0129291,0.00598636,-0....","0.00632094,0.0152186,0.0167812,0.0172992,0.001...","1.69357,0.413384,0.355528,0.13709,9.10019",0.009383,0.009383
38,2,rs3018727,61411534,"T,T,T,T,T","C,C,C,C,C","0.2365,0.0381,0.1212,0.1188,0.1414","-0.013557,0.0138858,-0.00741996,0.00195754,-0....","0.00625709,0.0152951,0.017017,0.0178566,0.0016...","1.51913,0.438955,0.178608,0.039669,9.40504",0.008838,0.008838
39,2,rs10750955,61392189,"T,NA,T,T,T","C,NA,C,C,C","0.2396,NA,0.12,0.1129,0.1339","-0.011069,NA,-0.0120871,-0.00200723,-0.0101979","0.00622914,NA,0.0170902,0.0182562,0.00165336","1.12164,NA,0.319294,0.0397905,9.16008",0.008328,0.008328
40,2,rs3018734,61443814,"A,NA,A,A,A","G,NA,G,G,G","0.1443,NA,0.0887,0.0667,0.1303","-0.0128674,NA,-0.00404005,-0.00158628,-0.0103591","0.00756656,NA,0.0195338,0.0231563,0.00167257","1.05049,NA,0.0777168,0.0243911,9.23041",0.007217,0.007217
41,2,rs4939517,61359386,"C,C,C,C,C","T,T,T,T,T","0.5965,0.0407,0.1415,0.1366,0.1356","-0.00680699,0.00561778,-0.0205705,0.0067096,-0...","0.00541958,0.0148185,0.0159343,0.0168233,0.001...","0.679613,0.152051,0.706157,0.161138,9.30889",0.006698,0.006698
42,2,rs10792314,61434831,"G,G,G,G,G","A,A,A,A,A","0.6325,0.0463,0.1729,0.1527,0.1544","-0.00578169,0.0107031,-0.0160585,0.0195175,-0....","0.00551485,0.0139342,0.014686,0.0160622,0.0015...","0.530973,0.354167,0.561944,0.649129,9.45244",0.006495,0.006495
43,2,rs3017602,61439326,"G,G,G,G,G","A,A,A,A,A","0.6347,0.0464,0.1732,0.1528,0.1544","-0.00600775,0.00997132,-0.0170991,0.0195691,-0...","0.00552183,0.01392,0.0146759,0.0160579,0.00155824","0.558156,0.324418,0.612655,0.651746,9.36631",0.006044,0.006044
44,2,rs4274208,61267020,"G,NA,G,NA,G","A,NA,A,NA,A","0.97775,NA,0.9226,NA,0.877","-0.0234177,NA,0.0226686,NA,0.0102866","0.0180266,NA,0.0207827,NA,0.00171431","0.712374,NA,0.560057,NA,8.706",0.005807,0.005807
45,2,rs61899464,61194987,"C,NA,C,NA,C","T,NA,T,NA,T","0.9807,NA,0.92874,NA,0.8944","-0.0147514,NA,0.00403169,NA,0.0112542","0.0193262,NA,0.0215879,NA,0.00183208","0.351354,NA,0.0696364,NA,9.09123",0.005600,0.005600
46,2,rs7118316,61380697,"A,A,A,A,A","G,G,G,G,G","0.6139,0.0173,0.1425,0.1346,0.1359","-0.00641483,0.0165388,-0.021616,0.011099,-0.01...","0.00546127,0.0224567,0.0158875,0.0169283,0.001...","0.619511,0.335883,0.760321,0.290687,9.08227",0.005218,0.005218
47,2,rs11230692,61422903,"T,NA,T,NA,T","C,NA,C,NA,C","0.0393,NA,0.0786,NA,0.1304","-0.00530242,NA,-0.0175883,NA,-0.0101221","0.0136837,NA,0.0206369,NA,0.00167203","0.155904,NA,0.404435,NA,8.84929",0.005080,0.005080
48,2,rs7933882,61441413,"T,T,T,T,T","C,C,C,C,C","0.6327,0.0464,0.1732,0.1524,0.154","-0.00560444,0.00977189,-0.016648,0.019637,-0.0...","0.00551548,0.01392,0.0146759,0.0160752,0.0015599","0.509244,0.316345,0.59068,0.653904,9.2806",0.004615,0.004615
49,2,rs879647,61437962,"G,G,G,G,G","A,A,A,A,A","0.6346,0.0464,0.1731,0.1527,0.1544","-0.00601132,0.0100112,-0.0161426,0.0197148,-0....","0.00552151,0.01392,0.0146793,0.0160622,0.00155824","0.558648,0.32604,0.566282,0.658229,9.2806",0.004565,0.004565
50,2,rs3019192,61500785,"A,NA,A,A,A","G,NA,G,G,G","0.1749,NA,0.0938,0.0618,0.1334","-0.00843269,NA,-0.000331283,0.00339969,-0.01012","0.00699913,NA,0.0190488,0.0239939,0.00165598","0.641545,NA,0.00606827,0.0519171,9.00481",0.004429,0.004429
51,2,rs6591654,61451709,"T,T,T,T,T","C,C,C,C,C","0.6337,0.0459,0.1728,0.1526,0.1542","-0.00569666,0.00990258,-0.0142736,0.0198718,-0...","0.00551864,0.0139919,0.0146894,0.0160665,0.001...","0.520063,0.319566,0.479909,0.665253,9.2806",0.003824,0.003824
52,2,rs3018735,61442973,"T,T,T,T,T","C,C,C,C,C","0.6337,0.0464,0.173,0.1527,0.1543","-0.00547413,0.00937304,-0.0171145,0.0196786,-0...","0.00551864,0.01392,0.0146826,0.0160622,0.00155866","0.493185,0.300402,0.613027,0.656552,9.1953",0.003648,0.003648
53,2,rs2943807,61428817,"G,G,G,G,G","A,A,A,A,A","0.6327,0.0462,0.1712,0.1518,0.153","-0.00582434,0.0110792,-0.0168105,0.0181547,-0....","0.00551548,0.0139486,0.0147436,0.0161012,0.001...","0.536154,0.369543,0.59481,0.585836,9.10019",0.003489,0.003489
54,2,rs748902,61474469,"T,NA,T,NA,T","G,NA,G,NA,G","0.0498,NA,0.0804,NA,0.1294","-0.00649462,NA,-0.0153667,NA,-0.0100672","0.0122228,NA,0.0204246,NA,0.00167751","0.225356,NA,0.345022,NA,8.70824",0.003404,0.003404

In [9]:
snp

,BP,SNP,PIP(CS1),"LogBF(CS1,Pop1)","LogBF(CS1,Pop2)","LogBF(CS1,Pop3)","LogBF(CS1,Pop4)","LogBF(CS1,Pop5)",PIP(CS2),"LogBF(CS2,Pop1)","LogBF(CS2,Pop2)","LogBF(CS2,Pop3)","LogBF(CS2,Pop4)","LogBF(CS2,Pop5)"
0,61000222,rs2905516,1.890870e-17,-0.659646,-1.395760e-10,-8.833080e-01,-2.753260e-10,-7.737970e-02,4.888940e-10,-0.696585,-1.395760e-10,-1.053750e+00,-2.753260e-10,-5.348240e-01
1,61000351,rs11230558,1.799620e-18,-0.431094,-1.403450e+00,-1.129690e+00,-9.554910e-01,-5.264940e-02,5.649950e-11,-0.202143,-1.393740e+00,-1.200090e+00,-9.938440e-01,-6.532520e-01
2,61000492,rs12791045,2.224120e-19,-1.211350,-4.724360e-01,-1.048000e+00,-1.104930e+00,-2.226470e+00,1.086310e-11,-1.185190,-4.222030e-01,-1.202990e+00,-1.094840e+00,-2.186700e+00
3,61000546,rs12797044,2.180060e-19,-1.213980,-4.762670e-01,-1.037850e+00,-1.105140e+00,-2.249950e+00,1.018620e-11,-1.188200,-4.261810e-01,-1.201590e+00,-1.095180e+00,-2.245120e+00
4,61000572,rs2905517,2.453750e-18,-0.055383,-4.223810e-01,-5.016490e-01,-5.094040e-01,-2.173520e+00,6.934770e-11,-0.017363,-4.677850e-01,-1.148450e+00,-4.965280e-01,-2.108050e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6032,62998397,rs4149183,1.002040e-17,-1.237420,-1.248610e+00,-3.151510e-01,-8.838310e-01,1.429680e+00,5.429310e-10,-1.246550,-1.304100e+00,-8.550390e-01,-8.276870e-01,2.053060e+00
6033,62998731,rs72933455,3.270790e-19,-1.280770,-1.416270e+00,-8.684650e-01,-2.753260e-10,-2.112010e+00,1.579610e-11,-1.287350,-1.412330e+00,-9.876090e-01,-2.753260e-10,-2.030250e+00
6034,62998762,rs73492018,9.945480e-18,-1.061470,-1.395760e-10,-1.201360e+00,-2.753260e-10,-2.824900e-11,5.329010e-10,-1.009960,-1.395760e-10,-1.189000e+00,-2.753260e-10,-2.824900e-11
6035,62998959,rs2276299,2.177900e-17,-0.190431,1.566050e+00,-1.172080e+00,-7.833620e-01,-8.991860e-01,1.290600e-09,-0.017174,1.485620e+00,-1.187090e+00,-7.661650e-01,-8.296320e-01
6036,62999198,rs3793961,1.556960e-17,-1.136190,-6.784450e-01,-3.128690e-10,-2.753260e-10,-2.824900e-11,8.200850e-10,-1.161670,-6.062300e-01,-3.128690e-10,-2.753260e-10,-2.824900e-11